/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cdt;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
	App app;
	@BeforeEach                                         
    void setUp() {
        app = new App();
    }
    @Test
	void testRound(){
		assertTrue(app.round(12.45, 1) == 12.5, "round() not working.");
    }
	@Test
	void testMonthlyPayment(){ //testing if the formula gives a correct output for a given set of input values
		double U = 1000;
		double b = 0.01;
		int p = 12;
		double sumOfInterest = 0;
		double remaining = U;
		double monthly = app.monthlyPayment(b, U, p);
		double thisInterest = 0;
		for(int i = 0; i < p; i++){
			thisInterest = remaining*b;
			sumOfInterest += thisInterest;
			remaining += thisInterest;
			remaining -= monthly;
		}
		assertTrue(app.round(monthly*p-U, 2) == app.round(sumOfInterest, 2), "monthlyPayment() not working");
	}
	
}
